#ifndef CONSTANTES_H_INCLUDED
#define CONSTANTES_H_INCLUDED

/* CONSTATNES DE ARCHIVOS */
#define PATH_ARCHIVO_TS "./ts.txt"
#define PATH_ARCHIVO_CODIGO_INTERMEDIO "./intermedio.txt"
#define PATH_ARCHIVO_ASSEMBLER "./Final.asm"
#define TEXTO_ESCRITURA "wt"
#define TEXTO_LECTURA "rt"
#define TEXTO_APPEND "at"
#define TEXTO_LECTURA_ESCRITURA "r+"

/* CONSTANTES DE RETORNOS GENERALES */
#define TODO_BIEN 0
#define ERROR 1

/* CONSTANTES DE LISTA */
#define LISTA_LLENA -1
#define LISTA_VACIA -2
#define LISTA_DUPLICADO -3
#define LISTA_NO_EXISTE_ELEMENTO -4

#define PRIMER_ELEMENTO 1
#define SEGUNDO_ELEMENTO 2
#define TERCER_ELEMENTO 1

/* CONSTANTES DE PILA */
#define PILA_LLENA -1
#define PILA_VACIA -2

/* CONSTANTES DE LEXICO */
#define LEXICO_CANTIDAD_COMILLAS 2
#define LEXICO_CANTIDAD_GUIONES_BAJOS 1
#define LEXICO_MAXIMA_CANTIDAD_CARACTERES_STRING 30
#define LEXICO_MAXIMA_CANTIDAD_CARACTERES_REAL 41
#define LEXICO_MAXIMO_VALOR_REAL 3.4e38
#define LEXICO_MAXIMA_CANTIDAD_CARACTERES_ENTERO 5
#define LEXICO_MAXIMO_VALOR_ENTERO 32768

#define LEXICO_TIPO_STRING "String"
#define LEXICO_TIPO_FLOAT "Float"
#define LEXICO_TIPO_INTEGER "Integer"

/* CONSTANTES DE SEMANTICA */
#define SEMANTICA_MAXIMA_LONGITUD_LISTA_DECLARACION 100

/* CONSTANTES DE TERCETOS */
#define TERCETO_CANTIDAD_CORCHETES 2
#define CANTIDAD_SALTOS_CONTAR 4

#define SIGNO_SUMAR "+"
#define SIGNO_RESTAR "-"
#define SIGNO_DIVISION "/"
#define SIGNO_MULT "*"

#define SIGNO_IGUAL ":="
#define SIGNO_VACIO " "

#define VARIABLE_CANT "@cant"
#define INI_VARIABLE_CANT "0"
#define AUMENTO_VARIABLE_CANT "1"
#define VARIABLE_AUX "@aux"

#define ENTRADA "GET"
#define SALIDA "PUT"
#define ETIQUETA "_ET_"

#define OPERADOR_LE "<"
#define OPERADOR_LEQ "<="
#define OPERADOR_GE	">"
#define OPERADOR_GEQ ">="
#define OPERADOR_NE	"<>"
#define OPERADOR_IGUAL "=="

#define CMP "CMP"
#define BI "BI"
#define BLT "BLT"
#define BLE "BLE"
#define BGT "BGT"
#define BGE "BGE"
#define BEQ "BEQ"
#define BNE "BNE"

#define CANTIDAD_DIGITOS_NUMERO 5

/* CONSTANTES DE ASSEMBLER */
#define PRECISION_STRING "db"
#define PRECISION_INTEGER "dd"
#define PRECISION_FLOAT "dd"
#define PRECISION_VARIABLE "dd"

#define FADD "FAAD"
#define FDIV "FDIV"
#define FSUB "FSUB"
#define FMUL "FMUL"

#define FLD "FLD"
#define FSTP "FSTP"

#define OUT_FLOAT "DisplayFloat"
#define OUT_STRING "displayStirng"


/* CONSTANTES GENERALES */
#define CANTIDAD_ITOA 1000

#endif // CONSTANTES_H_INCLUDED