#ifndef CONSTANTES_H_INCLUDED
#define CONSTANTES_H_INCLUDED

/* CONSTANTES DE RETORNOS GENERALES */
#define TODO_BIEN 0
#define ERROR 1

/* CONSTANTES DE LISTA */
#define LISTA_LLENA -1
#define LISTA_VACIA -2
#define LISTA_DUPLICADO -3
#define LISTA_NO_EXISTE_ELEMENTO -4

/* CONSTANTES DE COLA */
#define COLA_LLENA -4
#define COLA_VACIA -5

/* CONSTANTES DE LEXICO */
#define LEXICO_CANTIDAD_COMILLAS 2
#define LEXICO_CANTIDAD_GUIONES_BAJOS 1
#define LEXICO_MAXIMA_CANTIDAD_CARACTERES_STRING 30
#define LEXICO_MAXIMA_CANTIDAD_CARACTERES_REAL 41
#define LEXICO_MAXIMO_VALOR_REAL 3.4e38
#define LEXICO_MAXIMA_CANTIDAD_CARACTERES_ENTERO 5
#define LEXICO_MAXIMO_VALOR_ENTERO 32768

/* CONSTATNES DE ARCHIVOS */
#define PATH_ARCHIVO_TS "./ts.txt"
#define PATH_ARCHIVO_CODIGO_INTERMEDIO "./intermedio.txt"
#define TEXTO_ESCRITURA "wt"
#define TEXTO_LECTURA "rt"
#define TEXTO_APPEND "at"

/* CONSTANTES GENERALES */
#define CANTIDAD_ITOA 1000

#endif // CONSTANTES_H_INCLUDED